version: "3.2"
services:
  weston:
    image: torizon/arm64v8-debian-weston-vivante:latest
    privileged: true
    volumes:
      - type: bind
        source: /tmp
        target: /tmp

  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - type: volume
        source: portainer_data
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  kiosk:
    image: torizon/arm64v8-debian-kiosk-mode-browser:latest
    command: --window-mode http://portainer:9000
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
    depends_on:
      - portainer
      - weston

volumes:
  portainer_data:
